export const CABLE_CONSTANTS = {
  CALCULATION_VERSION: "1.0.0",

  MIN_DESIGN_MARGIN: 0,

  MAX_DESIGN_MARGIN: 1,

  MIN_POWER_FACTOR_EXCLUSIVE: 0,

  MAX_POWER_FACTOR: 1,

  MIN_CONDUCTOR_COUNT: 1,
} as const;