/**
 * PV Array validation error codes.
 *
 * These codes identify deterministic validation failures specific
 * to PV array configuration and electrical limits.
 */

export const PV_ARRAY_ERROR_CODES = {
  INVALID_MODULE_POWER:
    "PV_ARRAY_INVALID_MODULE_POWER",

  INVALID_MODULE_VMP:
    "PV_ARRAY_INVALID_MODULE_VMP",

  INVALID_MODULE_IMP:
    "PV_ARRAY_INVALID_MODULE_IMP",

  INVALID_MODULE_VOC:
    "PV_ARRAY_INVALID_MODULE_VOC",

  INVALID_MODULE_ISC:
    "PV_ARRAY_INVALID_MODULE_ISC",

  INVALID_MODULES_PER_STRING:
    "PV_ARRAY_INVALID_MODULES_PER_STRING",

  INVALID_PARALLEL_STRINGS:
    "PV_ARRAY_INVALID_PARALLEL_STRINGS",

  INVALID_MAX_VOLTAGE:
    "PV_ARRAY_INVALID_MAX_VOLTAGE",

  INVALID_MAX_CURRENT:
    "PV_ARRAY_INVALID_MAX_CURRENT",

  INVALID_MAX_POWER:
    "PV_ARRAY_INVALID_MAX_POWER",

  VMP_EXCEEDS_VOC:
    "PV_ARRAY_VMP_EXCEEDS_VOC",

  IMP_EXCEEDS_ISC:
    "PV_ARRAY_IMP_EXCEEDS_ISC",

  VOC_EXCEEDS_LIMIT:
    "PV_ARRAY_VOC_EXCEEDS_LIMIT",

  ISC_EXCEEDS_LIMIT:
    "PV_ARRAY_ISC_EXCEEDS_LIMIT",

  POWER_EXCEEDS_LIMIT:
    "PV_ARRAY_POWER_EXCEEDS_LIMIT",
} as const;

export type PvArrayErrorCode =
  (typeof PV_ARRAY_ERROR_CODES)[keyof typeof PV_ARRAY_ERROR_CODES];