/**
 * PV string validation error codes.
 *
 * These codes identify deterministic validation failures
 * specific to PV string calculations.
 */
export const PV_STRING_ERROR_CODES = {
  INVALID_MODULE_POWER:
    "PV_STRING_INVALID_MODULE_POWER",

  INVALID_MODULE_VMP:
    "PV_STRING_INVALID_MODULE_VMP",

  INVALID_MODULE_IMP:
    "PV_STRING_INVALID_MODULE_IMP",

  INVALID_MODULE_VOC:
    "PV_STRING_INVALID_MODULE_VOC",

  INVALID_MODULE_ISC:
    "PV_STRING_INVALID_MODULE_ISC",

  INVALID_MODULES_PER_STRING:
    "PV_STRING_INVALID_MODULES_PER_STRING",

  INVALID_MAX_STRING_VOLTAGE:
    "PV_STRING_INVALID_MAX_STRING_VOLTAGE",

  VMP_EXCEEDS_VOC:
    "PV_STRING_VMP_EXCEEDS_VOC",

  IMP_EXCEEDS_ISC:
    "PV_STRING_IMP_EXCEEDS_ISC",

  VOC_EXCEEDS_LIMIT:
    "PV_STRING_VOC_EXCEEDS_LIMIT",
} as const;

export type PvStringErrorCode =
  (typeof PV_STRING_ERROR_CODES)[keyof typeof PV_STRING_ERROR_CODES];