export const BOM_WARNING_CODES = {
  DUPLICATE_ITEM_MERGED: "DUPLICATE_ITEM_MERGED",
  OPTIONAL_SPECIFICATION_MISSING: "OPTIONAL_SPECIFICATION_MISSING",
  SPARE_QUANTITY_INCLUDED: "SPARE_QUANTITY_INCLUDED",
  NON_STANDARD_ITEM: "NON_STANDARD_ITEM",
  INCOMPLETE_SOURCE_INFORMATION: "INCOMPLETE_SOURCE_INFORMATION",
} as const;

export type BOMWarningCode =
  (typeof BOM_WARNING_CODES)[keyof typeof BOM_WARNING_CODES];