/**
 * Stable warning identifiers used throughout solar-engine.
 *
 * Codes are identifiers, not user-facing messages.
 * Applications may map them to localized or domain-specific text.
 */
export const WARNING_CODES = Object.freeze({
  GENERAL_ASSUMPTION: "SOLAR-W001",
  LOW_PERFORMANCE_RATIO: "SOLAR-W002",
  HIGH_PERFORMANCE_RATIO: "SOLAR-W003",

  HIGH_TEMPERATURE: "SOLAR-W010",
  LOW_TEMPERATURE: "SOLAR-W011",
  TEMPERATURE_DERATING: "SOLAR-W012",

  HIGH_VOLTAGE_DROP: "SOLAR-W020",
  LOW_VOLTAGE_MARGIN: "SOLAR-W021",
  CABLE_UTILIZATION_HIGH: "SOLAR-W022",

  PV_STRING_VOLTAGE_HIGH: "SOLAR-W030",
  PV_STRING_VOLTAGE_LOW: "SOLAR-W031",
  PV_MPPT_VOLTAGE_MARGIN_LOW: "SOLAR-W032",
  PV_ARRAY_OVERSIZE: "SOLAR-W033",

  INVERTER_UTILIZATION_HIGH: "SOLAR-W040",
  INVERTER_SURGE_MARGIN_LOW: "SOLAR-W041",
  INVERTER_TEMPERATURE_DERATING: "SOLAR-W042",

  BATTERY_DEPTH_OF_DISCHARGE_HIGH: "SOLAR-W050",
  BATTERY_AUTONOMY_LOW: "SOLAR-W051",
  BATTERY_TEMPERATURE_DERATING: "SOLAR-W052",
  BATTERY_UTILIZATION_HIGH: "SOLAR-W053",

  CONTROLLER_UTILIZATION_HIGH: "SOLAR-W060",
  CONTROLLER_INPUT_MARGIN_LOW: "SOLAR-W061",

  PROTECTION_RATING_LOW: "SOLAR-W070",
  PROTECTION_UTILIZATION_HIGH: "SOLAR-W071",

  GENERATOR_UTILIZATION_HIGH: "SOLAR-W080",
  GENERATOR_RESERVE_LOW: "SOLAR-W081",

  STANDARD_REFERENCE_REQUIRED: "SOLAR-W090",
  STANDARDS_COMPLIANCE_REVIEW: "SOLAR-W091",
} as const);

export type WarningCode =
  (typeof WARNING_CODES)[keyof typeof WARNING_CODES];